-- MySQL Script generated by MySQL Workbench
-- Tue Mar 11 19:57:03 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema TABLAS
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `TABLAS` ;

-- -----------------------------------------------------
-- Schema TABLAS
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `TABLAS` ;
USE `TABLAS` ;

-- -----------------------------------------------------
-- Table `TABLAS`.`GUARDERIAS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GUARDERIAS` ;

CREATE TABLE IF NOT EXISTS `TABLAS`.`GUARDERIAS` (
  `ID_Guarderia` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Direccion` VARCHAR(100) NOT NULL,
  `Telefono` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`ID_Guarderia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TABLAS`.`CUIDADOR`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CUIDADOR` ;

CREATE TABLE IF NOT EXISTS `TABLAS`.`CUIDADOR` (
  `ID_Cuidador` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Telefono` VARCHAR(20) NOT NULL,
  `ID_GUARDERIA` INT NOT NULL,
  PRIMARY KEY (`ID_Cuidador`),
  INDEX `ID_idx` (`ID_GUARDERIA` ASC) VISIBLE,
  CONSTRAINT `ID_Guarderia`
    FOREIGN KEY (`ID_GUARDERIA`)
    REFERENCES `TABLAS`.`GUARDERIAS` (`ID_Guarderia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TABLAS`.`PERRO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PERRO` ;

CREATE TABLE IF NOT EXISTS `TABLAS`.`PERRO` (
   `ID_Perro` INT NOT NULL AUTO_INCREMENT,
   `Nombre` VARCHAR(45) NOT NULL,
   `Raza` VARCHAR(45) NOT NULL,
   `Edad` INT NOT NULL,
   `Peso` DECIMAL(10,2) NOT NULL,
   `ID_GUARDERIA` INT NOT NULL,
   `ID_CUIDADOR` INT NOT NULL,
   PRIMARY KEY (`ID_Perro`),
   INDEX `ID_idx` (`ID_CUIDADOR` ASC) VISIBLE,
   INDEX `ID_idx1` (`ID_GUARDERIA` ASC) VISIBLE,
   CONSTRAINT `FK_PERRO_CUIDADOR` 
     FOREIGN KEY (`ID_CUIDADOR`) 
     REFERENCES `TABLAS`.`CUIDADOR` (`ID_Cuidador`) 
     ON DELETE NO ACTION 
     ON UPDATE NO ACTION,
   CONSTRAINT `FK_PERRO_GUARDERIA` 
     FOREIGN KEY (`ID_GUARDERIA`) 
     REFERENCES `TABLAS`.`GUARDERIAS` (`ID_Guarderia`) 
     ON DELETE NO ACTION 
     ON UPDATE NO ACTION)
ENGINE = InnoDB;



-- -----------------------------------------------------
-- Table `TABLAS`.`PROPIETARIOS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS`PROPIETARIOS` ;

CREATE TABLE IF NOT EXISTS `TABLAS`.`PROPIETARIOS` (
  `ID_Propietario` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Telefono` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`ID_Propietario`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
