-- MySQL Script generated by MySQL Workbench
-- Fri Apr  4 11:48:12 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Usar el esquema proporcionado por Railway
-- -----------------------------------------------------
USE `railway`;

-- -----------------------------------------------------
-- Table `ingrediente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ingrediente` ;

CREATE TABLE IF NOT EXISTS `ingrediente` (
  `idingrediente` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `precio` FLOAT NOT NULL,
  `tipo` ENUM('Base', 'Complemento') NOT NULL,
  `calorias` INT NOT NULL,
  `inventario` FLOAT NOT NULL,
  `es_vegetariano` TINYINT NOT NULL,
  `sabor` VARCHAR(50) NULL,
  PRIMARY KEY (`idingrediente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `producto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `producto` ;

CREATE TABLE IF NOT EXISTS `producto` (
  `idproductos` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `precio` FLOAT NOT NULL,
  `tipo` ENUM('Malteada', 'Copa') NOT NULL,
  `ingrediente1` INT NOT NULL,
  `ingrediente2` INT NOT NULL,
  `ingrediente3` INT NOT NULL,
  `volumen` FLOAT NULL,
  `tipo_vaso` VARCHAR(45) NULL,
  PRIMARY KEY (`idproductos`),
  INDEX `idingrediente_idx` (`ingrediente1` ASC) VISIBLE,
  INDEX `idingrediente_idx1` (`ingrediente2` ASC) VISIBLE,
  INDEX `idingrediente_idx2` (`ingrediente3` ASC) VISIBLE,
  CONSTRAINT `fk_ingrediente1`
    FOREIGN KEY (`ingrediente1`)
    REFERENCES `ingrediente` (`idingrediente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ingrediente2`
    FOREIGN KEY (`ingrediente2`)
    REFERENCES `ingrediente` (`idingrediente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ingrediente3`
    FOREIGN KEY (`ingrediente3`)
    REFERENCES `ingrediente` (`idingrediente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table Table `usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `usuario` ;

CREATE TABLE IF NOT EXISTS `usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(120) NOT NULL UNIQUE,
  `password` VARCHAR(255) NOT NULL,
  `es_admin` TINYINT NOT NULL,
  `es_empleado` TINYINT NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- Insertar ingredientes
INSERT INTO ingrediente (nombre, precio, tipo, calorias, inventario, es_vegetariano, sabor) VALUES
('Helado de Fresa', 1200, 'Base', 150, 10, 1, 'Fresa'),
('Helado de Vainilla', 1300, 'Base', 140, 10, 1, 'Vainilla'),
('Chispas de Chocolate', 500, 'Complemento', 50, 10, 1, NULL),
('Maní Japonés', 900, 'Complemento', 200, 10, 0, NULL),
('Sirope de Caramelo', 600, 'Complemento', 80, 15, 1, NULL),
('Nueces', 800, 'Complemento', 180, 12, 1, NULL);

-- Insertar productos
INSERT INTO producto (nombre, precio, tipo, tipo_vaso, volumen, ingrediente1, ingrediente2, ingrediente3) VALUES
('Copa Samurai', 7500, 'Copa', 'Cristal', NULL, 1, 3, 4),
('Malteada Chocoespacial', 8500, 'Malteada', NULL, 500, 1, 3, 4),
('Copa Dulce Encanto', 7800, 'Copa', 'Vidrio', NULL, 2, 5, 6),
('Malteada Caramelada', 8200, 'Malteada', NULL, 500, 2, 5, 6);

SELECT * FROM ingrediente;

SELECT * FROM producto;

SELECT p.idproductos, p.nombre AS nombre_producto, p.precio, p.tipo, p.tipo_vaso, p.volumen, 
  i1.nombre AS ingrediente1,
  i2.nombre AS ingrediente2,
  i3.nombre AS ingrediente3
FROM producto p
JOIN ingrediente i1 ON p.ingrediente1 = i1.idingrediente
JOIN ingrediente i2 ON p.ingrediente2 = i2.idingrediente
JOIN ingrediente i3 ON p.ingrediente3 = i3.idingrediente;

-- Insertar Usuarios
INSERT INTO usuario (username, password, es_admin, es_empleado) VALUES 
('admin', '1234', 1, 0),
('worker1', 'test', 0, 1),
('worker2', 'TEST', 0, 1),
('cliente1', 'qwerty', 0, 0),
('cliente2', 'asdfg', 0, 0);

SELECT * FROM usuario;