-- Punto 1 | Lassie 
SELECT * FROM TABLAS.PERROS WHERE Nombre = "Lassie";

-- Punto 2 | Los perros de Mario
SET SQL_SAFE_UPDATES = 0;
SELECT ID INTO @ID_Mario FROM TABLAS.CUIDADORES WHERE Nombre = 'Mario';
UPDATE TABLAS.PERROS SET ID_CUIDADOR = @ID_Mario WHERE Peso < 3;
SELECT * FROM TABLAS.PERROS WHERE ID_CUIDADOR = @ID_Mario;

-- PUNTO 3 | Guadería la Favorita
SELECT * FROM TABLAS.GUARDERIAS G 
JOIN TABLAS.CUIDADORES C ON G.ID = C.ID_GUARDERIA
JOIN TABLAS.PERROS P ON G.ID = P.ID_GUARDERIA
WHERE G.Nombre = "La Favorita";